# Generated by Django 5.1.7 on 2025-03-24 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('roleType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheckType',
            fields=[
                ('typeId', models.AutoField(primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=50)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.department')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('checkId', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.employee')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.team')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='teamId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.team'),
        ),
        migrations.CreateModel(
            name='HealthCheckVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('checkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.healthcheck')),
                ('typeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.healthchecktype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('checkId', 'typeId'), name='unique_vote')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.employee')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teamId', 'employeeId'), name='unique_employee_team')],
            },
        ),
    ]
