# Generated by Django 5.2 on 2025-04-28 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheckType',
            fields=[
                ('typeId', models.AutoField(primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('roleType', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=50)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.department')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('checkId', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.employee')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.team')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='teamId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthCheck.team'),
        ),
        migrations.CreateModel(
            name='HealthCheckVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('checkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.healthcheck')),
                ('typeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.healthchecktype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('checkId', 'typeId'), name='unique_vote')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.employee')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCheck.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teamId', 'employeeId'), name='unique_employee_team')],
            },
        ),
    ]
