# Generated by Django 5.2 on 2025-04-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='hasCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='hasStarted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='roleType',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('teamlead', 'Team Leader'), ('deptlead', 'Department Leader'), ('senior', 'Senior Manager')], max_length=50),
        ),
    ]
