# Generated by Django 5.2 on 2025-04-26 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='teamId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthCheck.team'),
        ),
    ]
