# Generated by Django 5.2 on 2025-04-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCheck', '0002_healthcheck_hascompleted_healthcheck_hasstarted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
