# Generated by Django 5.2 on 2025-04-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCheck', '0003_healthcheck_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheck',
            name='description',
        ),
        migrations.AddField(
            model_name='healthchecktype',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
